import Document, { Html, Head, Main, NextScript } from "next/document";

class MyDocument extends Document {
  render() {
    return (
      <Html>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" />
          <link
            href="https://fonts.googleapis.com/css2?family=Jost:wght@400;600;700&display=swap"
            rel="stylesheet"
          />
          <meta name="twitter:card" content="summary_large_image" />
          <meta
            name="twitter:site"
            content="https://feedback-dashboard-morfeli.vercel.app/"
          />
          <meta name="twitter:title" content="Feedback Dashboard" />
          <meta name="twitter:description" content="Public Blog Site" />
          <meta
            name="twitter:image"
            content="https://feedback-dashboard-morfeli.vercel.app/screenshot.png"
          />

          <meta property="og:type" content="website" />
          <meta property="og:title" content="Feedback Dashboard" />
          <meta property="og:description" content="Public Blog Site" />
          <meta
            property="og:url"
            content="https://feedback-dashboard-morfeli.vercel.app/"
          />
          <meta
            property="og:image"
            content="https://feedback-dashboard-morfeli.vercel.app/screenshot.png"
          />
        </Head>
        <body className="w-screen pb-8 font-serif bg-light-gray">
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
